artifacts_name: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestation
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestation/data.zip
  unzip_dir: artifacts/data_ingestation





prepare_base_model:
   root_dir: artifacts/prepare_base_model
   base_model_path: artifacts/prepare_base_model/base_model.h5
   updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
     


